### ISSUE TITLE
This configurations seem to be very different from angular-cli's tslint configuration.

### ISSUE THREAD

**Issue by xiaoxiangmoe** [mgechev/tslint-angular#16]
[Angular-CLI tslint.json.template](https://github.com/angular/angular-cli/blob/252f1be4f0a6c435b2b404983c5db7ff2dd8b0bd/packages/schematics/angular/workspace/files/tslint.json.template)

[tslint-angular](https://github.com/mgechev/tslint-angular/blob/b1b059e75c3e78e93c37f244661c0a8e13bfcc21/tslint.json)

These two configurations seem to be very different.

---

> Note: there are few more rules added on top of the Angular CLI configuration.

Can you tell me exactly what are the *rules added* ? This way I can know how to synchronize the angular-cli configuration to this project. Thanks.

**Comment by mgechev** [comment]
Hey @xiaoxiangmoe, some of the new rules are in [this](https://github.com/mgechev/tslint-angular/blob/master/tslint.json#L68-L82) section. Yes, the project got a little out of sync with the Angular CLI since we migrated to the `tslint:recommended` config. This repo still, however, contains mostly a stricter superset of the CLI's config.
